// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Ares API
//
//	oplanet consolidated api for ogame tools
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
