// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "oplanet consolidated api for ogame tools",
    "title": "Ares API",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/player": {
      "post": {
        "tags": [
          "player"
        ],
        "operationId": "getPlayer",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PlayerRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "get player information",
            "schema": {
              "type": "object",
              "additionalProperties": true
            }
          },
          "400": {
            "description": "bad request"
          },
          "404": {
            "description": "report not found"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "503": {
            "description": "Service Unavailable",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Countable": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer"
        },
        "technology": {
          "$ref": "#/definitions/TechnologyInfo"
        }
      }
    },
    "CountableMap": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/Countable"
      }
    },
    "Levelable": {
      "type": "object",
      "properties": {
        "level": {
          "type": "integer"
        },
        "technology": {
          "$ref": "#/definitions/TechnologyInfo"
        }
      }
    },
    "LevelableMap": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/Levelable"
      }
    },
    "Planet": {
      "type": "object",
      "properties": {
        "coordinates": {
          "type": "string"
        },
        "galaxy": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "position": {
          "type": "integer"
        },
        "system": {
          "type": "integer"
        },
        "type": {
          "type": "integer"
        }
      }
    },
    "PlayerData": {
      "type": "object",
      "properties": {
        "alliance": {
          "type": "object",
          "required": [
            "tag",
            "name"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "tag": {
              "type": "string"
            }
          }
        },
        "buildings": {
          "$ref": "#/definitions/LevelableMap"
        },
        "class": {
          "type": "integer"
        },
        "defence": {
          "$ref": "#/definitions/CountableMap"
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "planet": {
          "$ref": "#/definitions/Planet"
        },
        "research": {
          "$ref": "#/definitions/LevelableMap"
        },
        "resources": {
          "type": "object",
          "properties": {
            "crystal": {
              "type": "integer"
            },
            "deuterium": {
              "type": "integer"
            },
            "energy": {
              "type": "integer"
            },
            "metal": {
              "type": "integer"
            }
          }
        },
        "ships": {
          "$ref": "#/definitions/CountableMap"
        }
      }
    },
    "PlayerRequest": {
      "type": "object",
      "required": [
        "fleet",
        "key",
        "party"
      ],
      "properties": {
        "fleet": {
          "type": "integer",
          "format": "int64"
        },
        "key": {
          "type": "string",
          "pattern": "sr-.*"
        },
        "party": {
          "type": "string",
          "enum": [
            "attackers",
            "defenders"
          ]
        }
      }
    },
    "PlayerResponse": {
      "type": "object",
      "properties": {
        "data": {
          "type": "object"
        },
        "fleet": {
          "type": "integer",
          "format": "int64"
        },
        "party": {
          "type": "string"
        },
        "server": {
          "$ref": "#/definitions/ServerData"
        },
        "time": {
          "type": "number",
          "format": "float64"
        }
      }
    },
    "ServerData": {
      "type": "object",
      "properties": {
        "acs": {
          "type": "boolean"
        },
        "bash_limit": {
          "type": "integer"
        },
        "bonus_fields": {
          "type": "integer"
        },
        "cargo_hyperspace_tech_multiplier": {
          "type": "integer"
        },
        "characterClassesEnabled": {
          "type": "boolean"
        },
        "combatDebrisFieldLimit": {
          "type": "number"
        },
        "dark_matter_new_acount": {
          "type": "integer"
        },
        "debris_factor": {
          "type": "number"
        },
        "debris_factor_def": {
          "type": "number"
        },
        "def_to_tF": {
          "type": "boolean"
        },
        "domain": {
          "type": "string"
        },
        "donut_galaxy": {
          "type": "boolean"
        },
        "donut_system": {
          "type": "boolean"
        },
        "explorerBonusIncreasedExpeditionOutcome": {
          "type": "number"
        },
        "explorerBonusIncreasedResearchSpeed": {
          "type": "number"
        },
        "explorerBonusLargerPlanets": {
          "type": "number"
        },
        "explorerUnitItemsPerDay": {
          "type": "integer"
        },
        "galaxies": {
          "type": "integer"
        },
        "global_deuterium_save_factor": {
          "type": "number"
        },
        "language": {
          "type": "string"
        },
        "minerBonusAdditionalFleetSlots": {
          "type": "integer"
        },
        "minerBonusFasterTradingShips": {
          "type": "boolean"
        },
        "minerBonusIncreasedCargoCapacityForTradingShips": {
          "type": "number"
        },
        "minerBonusResourceProduction": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "newbie_protection_high": {
          "type": "integer"
        },
        "newbie_protection_limit": {
          "type": "integer"
        },
        "number": {
          "type": "integer"
        },
        "probe_cargo": {
          "type": "boolean"
        },
        "rapid_fire": {
          "type": "boolean"
        },
        "repair_factor": {
          "type": "number"
        },
        "research_duration_divisor": {
          "type": "integer"
        },
        "resourceBuggyEnergyConsumptionPerUnit": {
          "type": "integer"
        },
        "resourceBuggyMaxProductionBoost": {
          "type": "number"
        },
        "resourceBuggyProductionBoost": {
          "type": "number"
        },
        "speed": {
          "type": "integer"
        },
        "speed_fleet": {
          "type": "integer"
        },
        "systems": {
          "type": "integer"
        },
        "timezone": {
          "type": "string"
        },
        "timezone_offset": {
          "type": "string"
        },
        "top_score": {
          "type": "number"
        },
        "version": {
          "type": "string"
        },
        "warriorBonusFasterCombatShips": {
          "type": "boolean"
        },
        "warriorBonusFasterRecyclers": {
          "type": "boolean"
        },
        "warriorBonusRecyclerFuelConsumption": {
          "type": "number"
        },
        "wf_basic_percent_repairable": {
          "type": "integer"
        },
        "wf_enabled": {
          "type": "boolean"
        },
        "wf_min_loss_percent": {
          "type": "integer"
        },
        "wf_min_res_lost": {
          "type": "integer"
        }
      }
    },
    "SpyReport": {
      "type": "object",
      "properties": {
        "activity": {
          "type": "integer"
        },
        "attacker": {
          "$ref": "#/definitions/PlayerData"
        },
        "defender": {
          "$ref": "#/definitions/PlayerData"
        },
        "id": {
          "type": "string"
        },
        "loot_percentage": {
          "type": "integer"
        },
        "spy_fail_chance": {
          "type": "integer"
        },
        "time": {
          "type": "string"
        },
        "timestamp": {
          "type": "integer"
        },
        "total_defence_count": {
          "type": "integer"
        },
        "total_ship_count": {
          "type": "integer"
        }
      }
    },
    "TechnologyInfo": {
      "type": "object"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "oplanet consolidated api for ogame tools",
    "title": "Ares API",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/player": {
      "post": {
        "tags": [
          "player"
        ],
        "operationId": "getPlayer",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PlayerRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "get player information",
            "schema": {
              "type": "object",
              "additionalProperties": true
            }
          },
          "400": {
            "description": "bad request"
          },
          "404": {
            "description": "report not found"
          },
          "500": {
            "description": "Internal Server Error"
          },
          "503": {
            "description": "Service Unavailable",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Countable": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer"
        },
        "technology": {
          "$ref": "#/definitions/TechnologyInfo"
        }
      }
    },
    "CountableMap": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/Countable"
      }
    },
    "Levelable": {
      "type": "object",
      "properties": {
        "level": {
          "type": "integer"
        },
        "technology": {
          "$ref": "#/definitions/TechnologyInfo"
        }
      }
    },
    "LevelableMap": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/Levelable"
      }
    },
    "Planet": {
      "type": "object",
      "properties": {
        "coordinates": {
          "type": "string"
        },
        "galaxy": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "position": {
          "type": "integer"
        },
        "system": {
          "type": "integer"
        },
        "type": {
          "type": "integer"
        }
      }
    },
    "PlayerData": {
      "type": "object",
      "properties": {
        "alliance": {
          "type": "object",
          "required": [
            "tag",
            "name"
          ],
          "properties": {
            "name": {
              "type": "string"
            },
            "tag": {
              "type": "string"
            }
          }
        },
        "buildings": {
          "$ref": "#/definitions/LevelableMap"
        },
        "class": {
          "type": "integer"
        },
        "defence": {
          "$ref": "#/definitions/CountableMap"
        },
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "planet": {
          "$ref": "#/definitions/Planet"
        },
        "research": {
          "$ref": "#/definitions/LevelableMap"
        },
        "resources": {
          "type": "object",
          "properties": {
            "crystal": {
              "type": "integer"
            },
            "deuterium": {
              "type": "integer"
            },
            "energy": {
              "type": "integer"
            },
            "metal": {
              "type": "integer"
            }
          }
        },
        "ships": {
          "$ref": "#/definitions/CountableMap"
        }
      }
    },
    "PlayerDataAlliance": {
      "type": "object",
      "required": [
        "tag",
        "name"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "tag": {
          "type": "string"
        }
      }
    },
    "PlayerDataResources": {
      "type": "object",
      "properties": {
        "crystal": {
          "type": "integer"
        },
        "deuterium": {
          "type": "integer"
        },
        "energy": {
          "type": "integer"
        },
        "metal": {
          "type": "integer"
        }
      }
    },
    "PlayerRequest": {
      "type": "object",
      "required": [
        "fleet",
        "key",
        "party"
      ],
      "properties": {
        "fleet": {
          "type": "integer",
          "format": "int64"
        },
        "key": {
          "type": "string",
          "pattern": "sr-.*"
        },
        "party": {
          "type": "string",
          "enum": [
            "attackers",
            "defenders"
          ]
        }
      }
    },
    "PlayerResponse": {
      "type": "object",
      "properties": {
        "data": {
          "type": "object"
        },
        "fleet": {
          "type": "integer",
          "format": "int64"
        },
        "party": {
          "type": "string"
        },
        "server": {
          "$ref": "#/definitions/ServerData"
        },
        "time": {
          "type": "number",
          "format": "float64"
        }
      }
    },
    "ServerData": {
      "type": "object",
      "properties": {
        "acs": {
          "type": "boolean"
        },
        "bash_limit": {
          "type": "integer"
        },
        "bonus_fields": {
          "type": "integer"
        },
        "cargo_hyperspace_tech_multiplier": {
          "type": "integer"
        },
        "characterClassesEnabled": {
          "type": "boolean"
        },
        "combatDebrisFieldLimit": {
          "type": "number"
        },
        "dark_matter_new_acount": {
          "type": "integer"
        },
        "debris_factor": {
          "type": "number"
        },
        "debris_factor_def": {
          "type": "number"
        },
        "def_to_tF": {
          "type": "boolean"
        },
        "domain": {
          "type": "string"
        },
        "donut_galaxy": {
          "type": "boolean"
        },
        "donut_system": {
          "type": "boolean"
        },
        "explorerBonusIncreasedExpeditionOutcome": {
          "type": "number"
        },
        "explorerBonusIncreasedResearchSpeed": {
          "type": "number"
        },
        "explorerBonusLargerPlanets": {
          "type": "number"
        },
        "explorerUnitItemsPerDay": {
          "type": "integer"
        },
        "galaxies": {
          "type": "integer"
        },
        "global_deuterium_save_factor": {
          "type": "number"
        },
        "language": {
          "type": "string"
        },
        "minerBonusAdditionalFleetSlots": {
          "type": "integer"
        },
        "minerBonusFasterTradingShips": {
          "type": "boolean"
        },
        "minerBonusIncreasedCargoCapacityForTradingShips": {
          "type": "number"
        },
        "minerBonusResourceProduction": {
          "type": "number"
        },
        "name": {
          "type": "string"
        },
        "newbie_protection_high": {
          "type": "integer"
        },
        "newbie_protection_limit": {
          "type": "integer"
        },
        "number": {
          "type": "integer"
        },
        "probe_cargo": {
          "type": "boolean"
        },
        "rapid_fire": {
          "type": "boolean"
        },
        "repair_factor": {
          "type": "number"
        },
        "research_duration_divisor": {
          "type": "integer"
        },
        "resourceBuggyEnergyConsumptionPerUnit": {
          "type": "integer"
        },
        "resourceBuggyMaxProductionBoost": {
          "type": "number"
        },
        "resourceBuggyProductionBoost": {
          "type": "number"
        },
        "speed": {
          "type": "integer"
        },
        "speed_fleet": {
          "type": "integer"
        },
        "systems": {
          "type": "integer"
        },
        "timezone": {
          "type": "string"
        },
        "timezone_offset": {
          "type": "string"
        },
        "top_score": {
          "type": "number"
        },
        "version": {
          "type": "string"
        },
        "warriorBonusFasterCombatShips": {
          "type": "boolean"
        },
        "warriorBonusFasterRecyclers": {
          "type": "boolean"
        },
        "warriorBonusRecyclerFuelConsumption": {
          "type": "number"
        },
        "wf_basic_percent_repairable": {
          "type": "integer"
        },
        "wf_enabled": {
          "type": "boolean"
        },
        "wf_min_loss_percent": {
          "type": "integer"
        },
        "wf_min_res_lost": {
          "type": "integer"
        }
      }
    },
    "SpyReport": {
      "type": "object",
      "properties": {
        "activity": {
          "type": "integer"
        },
        "attacker": {
          "$ref": "#/definitions/PlayerData"
        },
        "defender": {
          "$ref": "#/definitions/PlayerData"
        },
        "id": {
          "type": "string"
        },
        "loot_percentage": {
          "type": "integer"
        },
        "spy_fail_chance": {
          "type": "integer"
        },
        "time": {
          "type": "string"
        },
        "timestamp": {
          "type": "integer"
        },
        "total_defence_count": {
          "type": "integer"
        },
        "total_ship_count": {
          "type": "integer"
        }
      }
    },
    "TechnologyInfo": {
      "type": "object"
    }
  }
}`))
}
