// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Countable countable
//
// swagger:model Countable
type Countable struct {

	// count
	Count int64 `json:"count,omitempty"`

	// technology
	Technology TechnologyInfo `json:"technology,omitempty"`
}

// Validate validates this countable
func (m *Countable) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this countable based on context it is used
func (m *Countable) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Countable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Countable) UnmarshalBinary(b []byte) error {
	var res Countable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
