// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Planet planet
//
// swagger:model Planet
type Planet struct {

	// coordinates
	Coordinates string `json:"coordinates,omitempty"`

	// galaxy
	Galaxy int64 `json:"galaxy,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// position
	Position int64 `json:"position,omitempty"`

	// system
	System int64 `json:"system,omitempty"`

	// type
	Type int64 `json:"type,omitempty"`
}

// Validate validates this planet
func (m *Planet) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this planet based on context it is used
func (m *Planet) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Planet) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Planet) UnmarshalBinary(b []byte) error {
	var res Planet
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
